### ISSUE TITLE
How can I early exiting by running easy stage only once？

### ISSUE THREAD

**Issue by yiyunchen** [RyanXingQL/RBQE#1]
Hello， I am interested in your work. But in your current release code part, the early exiting part is not contained in RBQE network.
You choose different 'order' to realize different exiting? 
Does your unpublished code have a more efficient implementation?

Than you!

**Comment by RyanXingQL** [comment]
Hi yunchen, thanks for your interest!

Following MSDNet and RANet, we output all enhanced images from all exits, and then calculate the Tchebichef scores to decide which enhanced image we should choose. This is convenient for us to conduct testing under different thresholds.

Unfortunately, we write our Tchebichef IQA code on MATLAB, and we haven't transfer it to Python yet. We are working on an updated version right now, and hopefully we can make it soon.

If you have any questions about implementation, feel free to contact us~
