### ISSUE TITLE
experimental detail

### ISSUE THREAD

**Issue by yiyunchen** [RyanXingQL/RBQE#3]
hello, I would like to confirm some experimental detail:
Input image is RGB image？
and PSNR and SSIM are calculated on y channel?

Thank you!

**Comment by RyanXingQL** [comment]
Hi yiyun
Thanks for your interest~

In our paper and programming, only Y channel is enhanced and accessed. That is, we measure and report the Y-PSNR.

The adopted RAISE dataset is in TIFF format. We first load TIFF images as RGB, transfer them into YCbCr 420P, and then compress them using HM. See [here](https://github.com/RyanXingQL/RBQE#13-compress-images).

For JPEG compression, we directly compress these TIFF images, and then transfer them into YCbCr 420P.

Therefore, the input image for enhancement is actually in the form of YCbCr 420P frame.
