### ISSUE TITLE
Training Details

### ISSUE THREAD

**Issue by BokaiLIAN** [RyanXingQL/RBQE#5]
Hi, Thanks for your work, which I'm interesting into, while got a question about the training detail.

In the bottom of the 11'th page( second paragraph of section 4.2 _Implementation Details_),  you mentioned a "easy to hard" paradigm and set {\omege_j} to different QP.
Does this mean the probability of groundtruth( or the path gradients backwards ) for img with a certain QP degradation.

Looking forward to your reply.

**Comment by RyanXingQL** [comment]
Hi Bokai, thanks so much for your insterest!

1. Our easy to hard training is as follows: for slightly distorted images, we encourage them to exit in the early exits; while for heavily distorted ones, we will not force them to exit early.
2. We do this by setting different weights of loss to exits.
3. This strategy can mitigate the interference between exits.

在这种多输出网络之中，每个输出之间一定会存在串扰。对于深出口，它们希望渐进提取特征和重建图像；然而，中间的特征图不得不被浅出口使用。关于这一点可以看 MSDNet。

为了减少这种串扰，我们可以让不同失真的图像尽量走不同的出口。根据 easy to hard 思想，我们让高质量图像先退出，低质量图像后退出。具体做法就是对不同出口的 loss 加权。

**Comment by BokaiLIAN** [comment]
Got the point of giving different weight to loss of each exits, Thanks for the timely reply !
Best of luck in the year to come.
