### ISSUE TITLE
Database Generation Code

### ISSUE THREAD

**Issue by miguellpcs** [RyanXingQL/RBQE#8]
Hello :)
I want to use your database to do some experiments to test my architecture.
I could not finding the code used to generate the HEVC-MSP-compressed set (main_tiff2yuv420p.m, main_compress.sh). 
Could you please share these scripts?

Thank you a lot. Have a nice day!

**Comment by ryanxingql** [comment]
Sure. Please refer to my doc: https://github.com/ryanxingql/powerqe/blob/v3/docs/v3.md#prepare-data

**Comment by miguellpcs** [comment]
In your paper "Early Exit Or Not: Resource-Efficient Blind
Quality Enhancement for Compressed Images", Section 4.1 Dataset:

> For JPEG, we use the JPEG encoder of Python Imaging Library (PIL) [27] to compress the cropped raw images with quality factor (QF) = 10, 20, 30, 40 and 50

I want to confirm if the dataset will be created using the following method:
Suppose we have a .TIFF image X from RAISE datataset, this text tells us that we will generate compressed images X_QF10, X_QF20 and so on...
By doing that, we'll have 5 for each image X training examples: (input = X_QF10, target = X;   input = X_QF20, target = X; and so on...)

Is it correct to do that? 
Thanks a lot!

**Comment by ryanxingql** [comment]
> In your paper "Early Exit Or Not: Resource-Efficient Blind Quality Enhancement for Compressed Images", Section 4.1 Dataset:
> 
> > For JPEG, we use the JPEG encoder of Python Imaging Library (PIL) [27] to compress the cropped raw images with quality factor (QF) = 10, 20, 30, 40 and 50
> 
> I want to confirm if the dataset will be created using the following method: Suppose we have a .TIFF image X from RAISE datataset, this text tells us that we will generate compressed images X_QF10, X_QF20 and so on... By doing that, we'll have 5 for each image X training examples: (input = X_QF10, target = X; input = X_QF20, target = X; and so on...)
> 
> Is it correct to do that? Thanks a lot!

Yes, each pair consists of a compressed image with its ground-truth counterpart.
